server:
  port: 8088
  servlet:
    context-path: '/agilebeaver'

logging:
  level:
    root: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
  file:
    name: "/var/log/app/agilebeaver.log"
  logback:
    rollingpolicy:
      max-history: 30

spring:
  application:
    name: 'agilebeaver-db-cm-liquibase'
  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"
  liquibase:
    change-log: 'classpath:db/changelog/db-changelog-master.yaml'
    # default-schema: 'agilebeaver'
  # jpa:
  #   properties:
  #     hibernate:
  #       default_schema: 'agilebeaver'
